teleop:
  walk:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: turtlesim1/turtle1/cmd_vel
    deadman_buttons: [0]
    axis_mappings:
      -
        axis: 1
        target: linear.x
        scale: 2.0
        offset: 0.0
      -
        axis: 0
        target: angular.z
        scale: 1.0
      -
        axis: 2
        target: linear.y
        scale: 2.0
      -
        button: 2
        target: linear.z
        scale: 2.0
