joy_teleop:
  ros__parameters:

    walk:
      type: topic
      interface_type: geometry_msgs/msg/Twist
      topic_name: cmd_vel
      deadman_buttons: [4]
      axis_mappings:
        linear-x:
          axis: 1
          scale: 0.5
          offset: -0.03
        angular-z:
          axis: 0
          scale: 0.5
        linear-y:
          axis: 2
          scale: 0.3
        linear-z:
          button: 2
          scale: 3.0